version: '3.8'

services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - HTTP_ADDR=${HTTP_ADDR}
      - HTTP_WRITE_TIMEOUT=${HTTP_WRITE_TIMEOUT}
      - HTTP_READ_TIMEOUT=${HTTP_READ_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}

      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
    depends_on:
      - postgres
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    ports:
      - '5433:5433'
    command: -p 5433 # because local postgres listens on port 5432 by default
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
